import img from '../assets/images/item.png';

export const mockMovies = {
  '58e008780aac31001185ed05': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '58e009390aac31001185ed10': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '588e746706ac2b00110e59ff': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '58e008ad0aac31001185ed0c': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '58e008ad0aac31001167df0c': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '58e008ad0aac31002267df0c': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '58e118ad0aac31001167df0c': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
  '01e118ad0aac31001167df0c': {
    status: { verified: true, sentCount: 1 },
    _id: '58e008780aac31001185ed05',
    movie: {
      name: 'Wonder Woman: 1984',
      poster: img,
      desc: 'In 1984, after saving the world in Wonder Woman (2017), the immortal Amazon warrior, Princess Diana of Themyscira, finds herself trying to stay under the radar, working as an archaeologist at the Smithsonian Museum. With the memory of the brave U.S. pilot, Captain Steve Trevor, etched on her mind, Diana Prince becomes embroiled in a sinister conspiracy of global proportions when a transparent, golden-yellow citrine gemstone catches the eye of the power-hungry entrepreneur, Maxwell Lord.',
      rating: { basic: 7.5, imdb: 7.6 },
      duration: '130',
      year: '2011',
      released: '2020-08-23T20:20:01.611Z',
      boxOffice: '$381,409,310',
      country: 'United Kingdom, United States',
      production: 'Heyday Films, Moving Picture Company, Warner Bros.',
      actors: 'Daniel Radcliffe, Emma Watson, Rupert Grint',
      director: 'David Yates',
      writers: 'J.K. Rowling, Steve Kloves',
      categories: ['adventure', 'action', 'fantasy'],
      saved: false,
    },
    __v: 0,
    source: 'movie',
    updatedAt: '2020-08-23T20:20:01.611Z',
    type: 'movie',
    createdAt: '2018-03-29T20:20:03.844Z',
    deleted: false,
    used: false,
  },
};
